//DECK

export const CHANGE_SLIDE = 'CHANGE_SLIDE';

//CONTAINER
export const UPDATE_ACTIVE_CONTAINER = 'UPDATE_ACTIVE_CONTAINER';

//EPISODE
export const LAUNCH_EPISODE = 'LAUNCH_EPISODE';

//HEADER
export const HEADER_VISIBILITY = 'HEADER_VISIBILITY';

//SLIDES
export const ADD_SLIDE = 'ADD_SLIDE';

//AUDIO
export const RUN_AUDIO = 'RUN_AUDIO';